name:  C/C++ CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make 
      run:  make Run -C M1_ElectricitytarrifCalc_Util/3_Implementation
   
